### ISSUE TITLE
setting surface color with CSS leads to "ghost" surfaces

### ISSUE THREAD

**Issue by stukennedy** [Famous/famous-angular#85]
Because the Famo.us framework creates its own version of the DOM, when we use Famous-Angular to define Famous surfaces we end up with ghost elements in the DOM that CSS is being applied to, requiring us to set `ng-hide=true` on elements that have CSS applied. Is there another way around this?

e.g. let's say we have a surface as follows

``` html
<fa-modifier fa-translate="[400,50]">
    <fa-surface fa-size="[100,100]" class="box">
        Text
    </fa-surface>
</fa-modifier>
```

and css

``` css
.box {
    padding: 10px;
    background-color: #333;
    color: #fff;
    border-style: solid;
    border-width: 2px;
    border-color: #444;
}
```

You will see an unsized copy of the surface at position `[0,0]`.
